# Generated by Django 2.1.1 on 2019-04-12 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190411_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='In_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(verbose_name='Основной')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Section')),
            ],
        ),
    ]
